
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres

development:
  <<: *default
  database: pacc_development


test:
  <<: *default
  database: pacc_test


production:
  <<: *default
  database: pacc_production
  username: pacc
  password: <%= ENV['PACC_DATABASE_PASSWORD'] %>
